name: Cargo Tests

on:
  push:
    paths:
      - 'saba_core/**'
  pull_request:
    paths:
      - 'saba_core/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-01
          components: rustfmt, rust-src
          targets: x86_64-unknown-linux-gnu

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        working-directory: ./saba_core
        run: cargo test 
